/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/integrations/github/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin GitHub App installation
         * @description Redirects the authenticated user to the GitHub App installation page. The installation must grant access only to repositories selected by the user or organization.
         */
        get: operations["beginGitHubInstallation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/github/installations/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Complete GitHub App installation
         * @description Validates the installation callback and records an opaque provider connection reference. Installation tokens and private keys are never returned to the caller.
         */
        get: operations["completeGitHubInstallation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/github/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List repositories available to the active GitHub installation */
        get: operations["listAuthorizedGitHubRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List connected repositories */
        get: operations["listRepositories"];
        put?: never;
        /**
         * Connect a repository
         * @description Registers a source repository accessible through the current user's configured provider connection. Provider details are accepted at this integration boundary and are not part of the core Repository model.
         */
        post: operations["createRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repositoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        /** Retrieve a connected repository */
        get: operations["getRepository"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repositoryId}/analysis-runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start repository analysis
         * @description Resolves the requested ref to an immutable revision before scheduling work. Active work for the same revision and analysis configuration is reused unless createDistinctRun is true.
         */
        post: operations["startAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** Retrieve analysis status and stage progress */
        get: operations["getAnalysisRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis-runs/{runId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        /** Retrieve analysis summary counts and issues */
        get: operations["getAnalysisSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GitHubRepositoryChoice: {
            /** @description Opaque provider identifier kept at the integration boundary. */
            providerRepositoryId: string;
            fullName: string;
            /** Format: uri */
            uri: string;
        };
        CreateRepositoryRequest: {
            source: {
                /**
                 * @description Provider adapter key; github is the initial supported value.
                 * @enum {string}
                 */
                provider: "github";
                /**
                 * Format: uri
                 * @description Canonical provider source address selected by the caller.
                 */
                uri: string;
            };
            displayName?: string;
        };
        Repository: {
            id: string;
            displayName: string;
            /** @enum {string} */
            state: "active" | "disconnected";
            /** Format: date-time */
            createdAt: string;
        };
        StartAnalysisRequest: {
            /** @description Optional branch, tag, or revision request; resolved and pinned before work is queued. */
            revision?: string;
            /**
             * @description Create a separate run instead of reusing active work for the same snapshot/configuration.
             * @default false
             */
            createDistinctRun: boolean;
        };
        AnalysisStage: {
            /** @enum {string} */
            name: "acquisition" | "file_discovery" | "language_detection" | "parsing" | "symbol_extraction" | "relationship_extraction" | "persistence";
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "partial" | "failed" | "skipped";
            attemptCount: number;
            progress?: {
                current?: number;
                total?: number;
            };
            error?: components["schemas"]["AnalysisError"];
        };
        AnalysisRun: {
            id: string;
            repositoryId: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "partial" | "failed";
            requestedRevision?: string;
            /** @description Opaque immutable provider revision identifier. */
            snapshotRevision?: string;
            stages: components["schemas"]["AnalysisStage"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            /**
             * Format: date-time
             * @description Time when a bounded transient retry becomes eligible for another worker claim.
             */
            nextAttemptAt?: string;
            /** @description Present on start responses; true when idempotency or active-run deduplication reused a run. */
            reused?: boolean;
            error?: components["schemas"]["AnalysisError"];
        };
        AnalysisSummary: {
            runId: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "partial" | "failed";
            counts: {
                files: number;
                projects: number;
                symbols: number;
                apis: number;
                tests: number;
                dependencies: number;
                relationships: number;
                unresolvedRelationships: number;
            };
            issues: components["schemas"]["AnalysisError"][];
        };
        AnalysisError: {
            code: string;
            /** @description Sanitized description; never includes credentials or full source. */
            message: string;
            stage?: string;
            /** @description Optional repository-relative affected path. */
            path?: string;
        };
    };
    responses: {
        /** @description Invalid request shape. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AnalysisError"];
            };
        };
        /** @description Caller is not authenticated. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Caller lacks access to the repository or workspace. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Repository or run does not exist or is not visible to the caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Idempotency key conflict or incompatible duplicate request. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AnalysisError"];
            };
        };
        /** @description Source cannot be resolved, accessed, or analyzed as requested. */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AnalysisError"];
            };
        };
    };
    parameters: {
        /** @description Optional caller key scoped to the authenticated workspace. Reuse with the same request returns the associated resource; a different request with the same key returns 409. */
        IdempotencyKey: string;
        RepositoryId: string;
        RunId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    beginGitHubInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to GitHub App installation. */
            302: {
                headers: {
                    /** @description GitHub App installation URL. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    completeGitHubInstallation: {
        parameters: {
            query: {
                state: string;
                installation_id: string;
                setup_action?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the repository connection experience. */
            303: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAuthorizedGitHubRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repositories available for the user to connect. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["GitHubRepositoryChoice"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connected repositories visible to the caller. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Repository"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createRepository: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional caller key scoped to the authenticated workspace. Reuse with the same request returns the associated resource; a different request with the same key returns 409. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRepositoryRequest"];
            };
        };
        responses: {
            /** @description Repository connected. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Repository resource. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repository"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    startAnalysis: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional caller key scoped to the authenticated workspace. Reuse with the same request returns the associated resource; a different request with the same key returns 409. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                repositoryId: components["parameters"]["RepositoryId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartAnalysisRequest"];
            };
        };
        responses: {
            /** @description Analysis run created or existing active run reused. */
            202: {
                headers: {
                    /** @description URL of the analysis run resource. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getAnalysisRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current or terminal analysis run state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRun"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getAnalysisSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary for a run, including explicit partial/failed state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
